# You can specify a custom docker image from Docker Hub as your build environment.
image: frekele/ant

pipelines:
  default:
    - step:
        script: 
        - pwd
    - step:
        script: 
        - ant con4-src/java/connectfour/build.xml