# You can specify a custom docker image from Docker Hub as your build environment.
image: frekele/ant:latest

pipelines:
  default:
    - step:
        script: 
        - ant -version
        - ls -la $BITBUCKET_CLONE_DIR/java/connectfour
        - cd $BITBUCKET_CLONE_DIR/java/connectfour
        - pwd
        - ant build.xml