# You can specify a custom docker image from Docker Hub as your build environment.
image: frekele/ant:latest

pipelines:
  default:
    - step:
        script: 
        - pwd
        - ant --version
        - ant $BITBUCKET_CLONE_DIR/java/connectfour/build.xml